In [1]:
import pandas as pd

In [2]:
data = {'Size': ['Medium', 'Small', 'Large', 'Medium', 'Large']}
df = pd.DataFrame(data)

In [3]:
df

     Size
0  Medium
1   Small
2   Large
3  Medium
4   Large

In [4]:
mapping = {
    'Small' : 10,
    'Medium' : 11,
    'Large' : 12
}

In [5]:
df['Size_encoded'] = df['Size'].map(mapping)

In [6]:
df

     Size  Size_encoded
0  Medium            11
1   Small            10
2   Large            12
3  Medium            11
4   Large            12

We can do it using replace also

In [7]:
df['Size_encoded_re'] = df['Size'].replace(mapping)

C:\Users\G M RIFAT REZA\AppData\Local\Temp\ipykernel_12668\4098541496.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Size_encoded_re'] = df['Size'].replace(mapping)

In [8]:
df

     Size  Size_encoded  Size_encoded_re
0  Medium            11               11
1   Small            10               10
2   Large            12               12
3  Medium            11               11
4   Large            12               12

<div style='text-align: center; font-size: 40px'> Difference between map()and replace()</div>

In [9]:
data = {'Size': ['Medium', 'Small', 'Large', 'Medium', 'Large', '', 'Extra Large']}
df = pd.DataFrame(data)

In [10]:
df

          Size
0       Medium
1        Small
2        Large
3       Medium
4        Large
5
6  Extra Large

In [11]:
mapping = {
    'Small' : 10,
    'Medium' : 11,
    'Large' : 12
}

In [18]:
df['Size_encoded_map'] = df['Size'].map(mapping)

In [19]:
df

          Size  Size_encoded_map
0       Medium              11.0
1        Small              10.0
2        Large              12.0
3       Medium              11.0
4        Large              12.0
5                            NaN
6  Extra Large               NaN

In [20]:
df['Size_encoded_rep'] = df['Size'].replace(mapping)

In [21]:
df

          Size  Size_encoded_map Size_encoded_rep
0       Medium              11.0               11
1        Small              10.0               10
2        Large              12.0               12
3       Medium              11.0               11
4        Large              12.0               12
5                            NaN
6  Extra Large               NaN      Extra Large

##### For map()
**Notice:**
* Extra Large” is NOT in the mapping (6).
* There is a black cell in the column (5).

**.map() converts unknowns and blank to NaN**
##### For replace()
**.replace() does NOT convert unknown values and blank to NaN.
It simply leaves them unchanged.**
**
##### 🔥 Super simple summary
* .map() → unknown values → NaN
* .replace() → unknown values → keep original

<div style='text-align: center; font-size: 40px;'>Custom mapping on multiple column</div>

In [25]:

# Sample DataFrame
df = pd.DataFrame({
    "Size": ["Small", "Medium", "Large", "Medium"],
    "Education": ["High School", "Bachelor", "Master", "PhD"],
    "Satisfaction": ["Low", "Medium", "High", "Very High"]
})

In [26]:
df

     Size    Education Satisfaction
0   Small  High School          Low
1  Medium     Bachelor       Medium
2   Large       Master         High
3  Medium          PhD    Very High

In [27]:

# Custom mappings for each ordinal column
size_map = {
    "Small": 0,
    "Medium": 1,
    "Large": 2
}

education_map = {
    "High School": 0,
    "Bachelor": 1,
    "Master": 2,
    "PhD": 3
}

satisfaction_map = {
    "Low": 0,
    "Medium": 1,
    "High": 2,
    "Very High": 3
}

In [28]:
# Apply custom mapping (column by column)
df["Size"] = df["Size"].map(size_map)
df["Education"] = df["Education"].map(education_map)
df["Satisfaction"] = df["Satisfaction"].map(satisfaction_map)

In [29]:
df

   Size  Education  Satisfaction
0     0          0             0
1     1          1             1
2     2          2             2
3     1          3             3